[package]
name = "deepseek_rust_example"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
langchain-rust = { git = "https://github.com/yzytom/langchain-rust"}
serde_json = "1.0.145"
tokio = "1.48.0"
